/*
 * generated by Xtext
 */
package tp4.gbs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GobstonsUiModule extends tp4.gbs.ui.AbstractGobstonsUiModule {
	public GobstonsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
