// grammar tp4.gbs.Gobstons with org.eclipse.xtext.xbase.Xbase
grammar tp4.gbs.Gobstons with org.eclipse.xtext.common.Terminals

generate gobstons "http://www.gbs.tp4/Gobstons"

ProcedureDeclaration:
	'procedure' 'Main' '()' '{' 
    	(operations+=Operation)*
    '}';
    
Operation:
	Mover | Poner;

Mover:
	'Mover''('param=Direccion')';

Poner:
	'Poner''('param=Color')';

Direccion:
	'Norte' | 'Sur' | 'Este' | 'Oeste';

Color:
	'Rojo' | 'Verde' | 'Azul' | 'Negro';