/*
 * generated by Xtext
 */
package tp4.gbs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GobstonsRuntimeModule extends tp4.gbs.AbstractGobstonsRuntimeModule {

}
