/*
* generated by Xtext
*/
package tp4.gbs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GobstonsStandaloneSetup extends GobstonsStandaloneSetupGenerated{

	public static void doSetup() {
		new GobstonsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

