/*
 * generated by Xtext
 */
package tp4.gbs.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import tp4.gbs.ui.internal.GobstonsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GobstonsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GobstonsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GobstonsActivator.getInstance().getInjector(GobstonsActivator.TP4_GBS_GOBSTONS);
	}
	
}
