/**
 * generated by Xtext
 */
package tp4.gbs.ui.contentassist;

import tp4.gbs.ui.contentassist.AbstractGobstonsProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class GobstonsProposalProvider extends AbstractGobstonsProposalProvider {
}
