/*
* generated by Xtext
*/
package tp4.gbs.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tp4.gbs.services.GobstonsGrammarAccess;

public class GobstonsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GobstonsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected tp4.gbs.parser.antlr.internal.InternalGobstonsParser createParser(XtextTokenStream stream) {
		return new tp4.gbs.parser.antlr.internal.InternalGobstonsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}
	
	public GobstonsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GobstonsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
