/**
 * generated by Xtext
 */
package tp4.gbs.validation;

import tp4.gbs.validation.AbstractGobstonsValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GobstonsValidator extends AbstractGobstonsValidator {
}
